# We don't want to start from scratch.
# That is why we tell node here to use the current node image as base.
FROM node:alpine
# Create an application directory
RUN mkdir -p /app
# The /app directory should act as the main application directory
WORKDIR /app
COPY package*.json ./
# Install node packages
RUN npm install

COPY . .
RUN npm run build

# Start the app
CMD [ "npm", "start" ]