version: "0"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports: [9696:9696]
    container_name: api
  client:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports: [80:80]
    container_name: web
    