version: "3.8"
services:
  api:
    image: "api:latest"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9696:9696"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: python main.py
    